apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 81
        command: ['sh', '-c', '/sbin/sysctl', '-w', 'net.ipv6.conf.all.disable_ipv6=1']
