apiVersion: v1
kind: Namespace
metadata:
  name: nuvym
---
######################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nuvym-nginx-pv
spec:
  storageClassName: nuvym-nginx-storage-class
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/nfs/storage/nuvym"
---
#####################################################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nuvym-nginx-claim
   namespace: nuvym
spec:
  storageClassName: nuvym-nginx-storage-class
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
---
#####################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nuvym-nginx-etc-pv
spec:
  storageClassName: nuvym-nginx-etc-storage-class
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/nfs/storage/nuvym-nginx-etc"
---
#####################################################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nuvym-nginx-etc-claim
   namespace: nuvym
spec:
  storageClassName: nuvym-nginx-etc-storage-class
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
######################################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuvym-deployment
  namespace: nuvym
  labels:
    app: nuvym-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuvym-app
  template:
    metadata:
      labels:
        app: nuvym-app
    spec:
      volumes: 
        - name: nuvym-nginx-vol
          persistentVolumeClaim:
            claimName: nuvym-nginx-claim
        - name: nuvym-nginx-etc-vol
          persistentVolumeClaim:
            claimName: nuvym-nginx-etc-claim
      containers:
      - name: nuvym
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
           - name: nuvym-nginx-vol
             mountPath: "/usr/share/nginx/"
           - name: nuvym-nginx-etc-vol
             mountPath: "/etc/nginx"
        startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 15  
        livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 15
        readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 2
            periodSeconds: 10
        resources:
            limits:
              memory: "30M"
              cpu: "50m"
---
####################################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: nuvym-elb
  namespace: nuvym
spec:
  selector:
    app: nuvym-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32222